services:
  - type: web
    name: laxmifarmhouse
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn laxmifarmhouse.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: laxmifarmhouse.settings
